# Generated by Django 5.1.2 on 2024-10-26 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidence',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
