# Generated by Django 5.1.2 on 2024-10-26 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_scanresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanresult',
            name='files_found',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='scanresult',
            name='files_restored',
            field=models.IntegerField(default=0),
        ),
    ]
