# Generated by Django 5.1.2 on 2024-10-26 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0005_alter_scanresult_files_found_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanresult',
            name='deleted_files',
            field=models.TextField(blank=True, default='[]'),
        ),
        migrations.AlterField(
            model_name='scanresult',
            name='files_found',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='scanresult',
            name='files_restored',
            field=models.IntegerField(),
        ),
    ]
